from pydantic import BaseModel, Field, ConfigDict
from typing import Dict, List, Optional

class CriterionReadinessBase(BaseModel):
    criterion_id: str = Field(..., description="Unique code for the criterion (e.g., criterion1)")
    name: str = Field(..., description="Human-readable name of the criterion")
    score: float = Field(..., description="Readiness score percentage between 0 and 100", ge=0, le=100)

class CriterionReadiness(CriterionReadinessBase):
    id: int

    model_config = ConfigDict(from_attributes=True)

class DocumentBase(BaseModel):
    file_name: str = Field(..., description="The name of the uploaded file")
    status: str = Field(..., description="Status of the document (validated, pending, rejected)")
    criterion_id: str = Field(..., description="Criterion this document is submitted for")
    document_type: str = Field(..., description="The type/category of the document (e.g., Faculty Training Certificates)")

class DocumentCreate(DocumentBase):
    pass

class DocumentUpdateStatus(BaseModel):
    status: str = Field(..., description="New status of the document: validated, pending, or rejected")

class DocumentSchema(DocumentBase):
    id: int

    model_config = ConfigDict(from_attributes=True)

class DocumentMetrics(BaseModel):
    validated: int = Field(0, description="Count of validated documents")
    pending: int = Field(0, description="Count of pending documents")
    rejected: int = Field(0, description="Count of rejected documents")

class DashboardResponse(BaseModel):
    overall_readiness: int = Field(..., description="Overall readiness score calculated across criteria")
    criteria_readiness: Dict[str, int] = Field(..., description="Readiness percentage breakdown per criterion")
    document_metrics: DocumentMetrics = Field(..., description="Breakdown of document verification states")
    recommendations: List[str] = Field(..., description="Actionable recommendations generated by the recommendation agent")
